// Generated by chasi-ts sdkBuilder — do not edit manually.
// Host: http://localhost:3011
// Client: fetch

const HOST = "http://localhost:3011";

async function _request(method, path, payload, token) {
  const headers = { "Content-Type": "application/json" };
  if (token) headers["Authorization"] = `Bearer ${token}`;
  const options = { method: method.toUpperCase(), headers };
  if (payload && method.toLowerCase() !== "get") options.body = JSON.stringify(payload);
  const res = await fetch(HOST + path, options);
  if (!res.ok) {
    const err = await res.json().catch(() => ({ message: res.statusText, status: res.status }));
    throw err;
  }
  return res.json().catch(() => null);
}

function _validate(payload = {}, required = []) {
  for (const field of required) {
    const val = payload[field];
    if (val === undefined || val === null || val === "") {
      throw { status: 422, message: `[SDK] Missing required field: "${field}"` };
    }
  }
}

export const apiUsers = {
  /** POST /api/users/signin · public */
  signin: async (payload = {}) => {
    _validate(payload, ["email","pass"]);
    return _request("post", "/api/users/signin", payload);
  },
  /** POST /api/users/signup · public */
  signup: async (payload = {}) => {
    _validate(payload, ["name","email","alias","password"]);
    return _request("post", "/api/users/signup", payload);
  },
  /** POST /api/users/pg-signup · public */
  pgSignup: async (payload = {}) => {
    _validate(payload, ["name","email","alias","password"]);
    return _request("post", "/api/users/pg-signup", payload);
  },
};

export default { apiUsers };
