import fs from "fs";
import path from "path";
import type {
  SdkBuilderConfig,
  SdkBuildContext,
  SdkRouteEntry,
} from "./SdkBuilder.types.js";
import type RouteCollector from "./collectors/Routes.js";

// ─── Compiler ────────────────────────────────────────────────────────────────

export default class Compiler {
  constructor(
    private readonly config: SdkBuilderConfig,
    private readonly collector: RouteCollector
  ) {}

  // ─── Public entry ──────────────────────────────────────────────────────────

  async compile(): Promise<void> {
    await this.runSdkValidation();
    const code = this.generateBundle();
    await this.write(code);
  }

  // ─── sdk() build-phase validation ─────────────────────────────────────────

  /**
   * Iterates every collected route that has .sdk() handlers registered and
   * calls endpoint.runSdk(context) — executing the handler chain with a
   * SdkBuildContext so developers can validate route configuration at build
   * time rather than at request time.
   *
   * Failures are logged as warnings; they do not block code generation.
   */
  private async runSdkValidation(): Promise<void> {
    for (const route of this.collector.routes) {
      if (!route.hasSdkHandlers) continue;

      const context: SdkBuildContext = { config: this.config, route };

      try {
        let index = 0;
        const next = async (): Promise<void> => {
          if (index >= route.sdkHandlers.length) return;
          await route.sdkHandlers[index++](context, next);
        };
        await next();
        Logger.log(
          `[SdkBuilder] sdk() ✓ ${route.method.toUpperCase()} ${route.path}`
        );
      } catch (err: any) {
        Logger.log(
          `[SdkBuilder] sdk() ✗ ${route.method.toUpperCase()} ${route.path} — ${err?.message ?? err}`
        );
      }
    }
  }

  // ─── Bundle generation ─────────────────────────────────────────────────────

  private generateBundle(): string {
    const { httpClient = "fetch", host } = this.config;
    const lines: string[] = [];

    lines.push(`// Generated by chasi-ts sdkBuilder — do not edit manually.`);
    lines.push(`// Host: ${host}`);
    lines.push(`// Client: ${httpClient}`);
    lines.push(``);

    if (httpClient === "axios") {
      lines.push(`import axios from "axios";`);
      lines.push(``);
    }

    lines.push(`const HOST = ${JSON.stringify(host)};`);
    lines.push(``);
    lines.push(this.generateRequestHelper(httpClient));
    lines.push(``);
    lines.push(this.generateValidateHelper());
    lines.push(``);

    const hasSdkHandlers = this.collector.routes.some((r) => r.hasSdkHandlers);
    if (hasSdkHandlers) {
      lines.push(this.generateRunSdkHelper());
      lines.push(``);
    }

    const tree = this.buildNamespaceTree();
    const nsKeys: string[] = [];

    for (const [ns, routes] of Object.entries(tree)) {
      nsKeys.push(ns);
      lines.push(...this.generateNamespace(ns, routes));
      lines.push(``);
    }

    lines.push(`export default { ${nsKeys.join(", ")} };`);

    return lines.join("\n");
  }

  // ─── Namespace tree ────────────────────────────────────────────────────────

  /**
   * Groups routes by their first namespace segment.
   * Routes with no namespace are grouped under their function name
   * as a single-entry namespace.
   */
  private buildNamespaceTree(): Record<string, SdkRouteEntry[]> {
    const tree: Record<string, SdkRouteEntry[]> = {};

    for (const route of this.collector.routes) {
      const key =
        route.namespace.length > 0
          ? this.toCamelCase(route.namespace.join("_"))
          : route.functionName;

      if (!tree[key]) tree[key] = [];
      tree[key].push(route);
    }

    return tree;
  }

  // ─── Namespace block ───────────────────────────────────────────────────────

  private generateNamespace(ns: string, routes: SdkRouteEntry[]): string[] {
    const lines: string[] = [];
    lines.push(`export const ${ns} = {`);
    for (const route of routes) {
      lines.push(...this.generateRouteFunction(route, "  "));
    }
    lines.push(`};`);
    return lines;
  }

  // ─── Route function ────────────────────────────────────────────────────────

  private generateRouteFunction(route: SdkRouteEntry, indent: string): string[] {
    const args: string[] = [];
    const needsBody =
      !["get", "delete", "head"].includes(route.method.toLowerCase());

    if (needsBody) args.push("payload = {}");
    if (route.isProtected) args.push("token");

    const required = JSON.stringify(route.requiredFields);
    const payloadArg = needsBody ? "payload" : "null";
    const tokenArg = route.isProtected ? ", token" : "";
    const sdkParam = needsBody ? "payload" : "null";

    const meta: string[] = [
      `${route.method.toUpperCase()} ${route.path}`,
      route.isProtected ? "protected" : "public",
    ];
    if (route.middlewares.length) meta.push(`mw: [${route.middlewares.join(", ")}]`);
    if (route.hasSdkHandlers) meta.push("sdk() validated");

    const lines: string[] = [
      `${indent}/** ${meta.join(" · ")} */`,
      `${indent}${route.functionName}: async (${args.join(", ")}) => {`,
    ];

    // required-field validation from spec
    if (needsBody) {
      lines.push(`${indent}  _validate(payload, ${required});`);
    }

    // inline sdk() handlers — serialised and executed before the request
    if (route.hasSdkHandlers) {
      const serialized = route.sdkHandlers
        .map((fn) => fn.toString())
        .join(`,\n${indent}    `);
      lines.push(`${indent}  await _runSdk(${sdkParam}, [`);
      lines.push(`${indent}    ${serialized}`);
      lines.push(`${indent}  ]);`);
    }

    lines.push(
      `${indent}  return _request("${route.method}", ${JSON.stringify(route.path)}, ${payloadArg}${tokenArg});`,
      `${indent}},`
    );

    return lines;
  }

  // ─── _runSdk helper ────────────────────────────────────────────────────────

  private generateRunSdkHelper(): string {
    return [
      `async function _runSdk(params, handlers) {`,
      `  let i = 0;`,
      `  const next = async () => {`,
      `    if (i >= handlers.length) return;`,
      `    await handlers[i++](params, next);`,
      `  };`,
      `  await next();`,
      `}`,
    ].join("\n");
  }

  // ─── _request helper ───────────────────────────────────────────────────────

  private generateRequestHelper(client: string): string {
    if (client === "axios") {
      return [
        `async function _request(method, path, payload, token) {`,
        `  const headers = { "Content-Type": "application/json" };`,
        `  if (token) headers["Authorization"] = \`Bearer \${token}\`;`,
        `  try {`,
        `    const res = await axios({ method, url: HOST + path, headers, data: payload });`,
        `    return res.data;`,
        `  } catch (err) {`,
        `    throw err?.response?.data ?? { message: err.message };`,
        `  }`,
        `}`,
      ].join("\n");
    }

    return [
      `async function _request(method, path, payload, token) {`,
      `  const headers = { "Content-Type": "application/json" };`,
      `  if (token) headers["Authorization"] = \`Bearer \${token}\`;`,
      `  const options = { method: method.toUpperCase(), headers };`,
      `  if (payload && method.toLowerCase() !== "get") options.body = JSON.stringify(payload);`,
      `  const res = await fetch(HOST + path, options);`,
      `  if (!res.ok) {`,
      `    const err = await res.json().catch(() => ({ message: res.statusText, status: res.status }));`,
      `    throw err;`,
      `  }`,
      `  return res.json().catch(() => null);`,
      `}`,
    ].join("\n");
  }

  // ─── _validate helper ─────────────────────────────────────────────────────

  private generateValidateHelper(): string {
    return [
      `function _validate(payload = {}, required = []) {`,
      `  for (const field of required) {`,
      `    const val = payload[field];`,
      `    if (val === undefined || val === null || val === "") {`,
      `      throw { status: 422, message: \`[SDK] Missing required field: "\${field}"\` };`,
      `    }`,
      `  }`,
      `}`,
    ].join("\n");
  }

  // ─── File writer ───────────────────────────────────────────────────────────

  private async write(code: string): Promise<void> {
    const { filename, formatter } = this.config.output;

    // Normalise whitespace in the raw output, then hand off to the formatter
    let content = code.replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";

    if (formatter) {
      try {
        content = (await formatter(content)) ?? content;
      } catch (err) {
        Logger.log(`[SdkBuilder] formatter failed, writing unformatted output: ${err}`);
      }
    }

    // Always resolve relative to the project root (process.cwd())
    const outPath = path.resolve(process.cwd(), filename);
    const outDir  = path.dirname(outPath);

    try {
      await fs.promises.mkdir(outDir, { recursive: true });
      await fs.promises.writeFile(outPath, content, "utf-8");
      Logger.log(`[SdkBuilder] SDK written → ${filename}`);
    } catch (err) {
      Logger.log(`[SdkBuilder] failed to write SDK: ${err}`);
    }
  }

  // ─── Helpers ──────────────────────────────────────────────────────────────

  private toCamelCase(str: string): string {
    return str.replace(/[-_](.)/g, (_, c: string) => c.toUpperCase());
  }
}
